MultiProgressBar Class Reference
#include <MultiProgressBar.h>
Public Member Functions
 MultiProgressBar (vector< double > xmin, vector< double > xmax, vector< string > title)
 MultiProgressBar (double total, int color=0)
 ~MultiProgressBar ()
void Update (double current_pos=-1)
void Update (vector< double >current_pos)
Protected Attributes
vector< string > m_bar_str
int m_length_bar
char m_bar_char_left
char m_bar_char_right
vector< double > m_percent
vector< string > m_title
vector< double > m_total
vector< double > m_current_index
int m_bar_number
vector< double > m_left
vector< double > m_right
int m_maxLength_title
Private Member Functions
void init_colors ()
Private Attributes
double m_factor
vector< string > m_colors
int m_defaultcolor
Detailed Description
Definition at line 14 of file MultiProgressBar.h.
Constructor & Destructor Documentation
MultiProgressBar() [1/2]
MultiProgressBar::MultiProgressBar (vector< double > xmin, vector< double > xmax, vector< string > title)
Definition at line 38 of file MultiProgressBar.cpp.
References init_colors(), m_bar_char_right, m_bar_str, m_current_index, m_factor, m_left, m_length_bar, m_maxLength_title, m_percent, m_right, m_title, and m_total.
MultiProgressBar() [2/2]
MultiProgressBar::MultiProgressBar (double total, int color = 0)
Definition at line 16 of file MultiProgressBar.cpp.
References init_colors(), m_bar_char_right, m_bar_str, m_current_index, m_factor, m_left, m_length_bar, m_percent, m_right, m_title, and m_total.
~MultiProgressBar()
MultiProgressBar::~MultiProgressBar ()
Definition at line 13 of file MultiProgressBar.cpp.
Member Function Documentation
init_colors()
void MultiProgressBar::init_colors () [private]
Definition at line 5 of file MultiProgressBar.cpp.
References m_colors.
Referenced by MultiProgressBar().
Update() [1/2]
void MultiProgressBar::Update (double current_pos = -1)
Definition at line 76 of file MultiProgressBar.cpp.
References m_current_index, and m_total.
Referenced by DWC_p2p_CGLS(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_s2p_Tikhonov(), Getkernel_p2p(), Getkernel_p2p_new(), and Getkernel_p2s_new().
Update() [2/2]
void MultiProgressBar::Update (vector< double > current_pos)
Definition at line 84 of file MultiProgressBar.cpp.
References COLOR_DEFALUT, m_bar_char_left, m_bar_char_right, m_bar_str, m_colors, m_defaultcolor, m_factor, m_left, m_length_bar, m_maxLength_title, m_percent, m_title, m_total, and MOVEUP.
Member Data Documentation
m_bar_char_left
char MultiProgressBar::m_bar_char_left [protected]
Definition at line 25 of file MultiProgressBar.h.
Referenced by Update().
m_bar_char_right
char MultiProgressBar::m_bar_char_right [protected]
Definition at line 26 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_bar_number
int MultiProgressBar::m_bar_number [protected]
Definition at line 31 of file MultiProgressBar.h.
m_bar_str
vector<string> MultiProgressBar::m_bar_str [protected]
Definition at line 23 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_colors
vector<string> MultiProgressBar::m_colors [private]
Definition at line 36 of file MultiProgressBar.h.
Referenced by init_colors(), and Update().
m_current_index
vector<double> MultiProgressBar::m_current_index [protected]
Definition at line 30 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_defaultcolor
int MultiProgressBar::m_defaultcolor [private]
Definition at line 38 of file MultiProgressBar.h.
Referenced by Update().
m_factor
double MultiProgressBar::m_factor [private]
Definition at line 35 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_left
vector<double> MultiProgressBar::m_left [protected]
Definition at line 32 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_length_bar
int MultiProgressBar::m_length_bar [protected]
Definition at line 24 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_maxLength_title
int MultiProgressBar::m_maxLength_title [protected]
Definition at line 33 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_percent
vector<double> MultiProgressBar::m_percent [protected]
Definition at line 27 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_right
vector<double> MultiProgressBar::m_right [protected]
Definition at line 32 of file MultiProgressBar.h.
Referenced by MultiProgressBar().
m_title
vector<string> MultiProgressBar::m_title [protected]
Definition at line 28 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
m_total
vector<double> MultiProgressBar::m_total [protected]
Definition at line 29 of file MultiProgressBar.h.
Referenced by MultiProgressBar(), and Update().
The documentation for this class was generated from the following files:
 MultiProgressBar.h
 MultiProgressBar.cpp