Conti2D.h File Reference
#include <sstream>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <vector>
#include <math.h>
#include `omp.h`
#include `FFTN.h`
#include `MultiProgressBar.h`
#include <unistd.h>
Classes
struct GrdHead
head information of a grid data, e.g.
Macros
#define PI 3.141592653
#define DWC_CGLS 1
#define DWC_TIKHONOV 2
#define DWC_INTEGRALITERATION 3
#define DWC_LANDWEBER 4
#define ERROR_COUT `[`<<`\033[31mError`<<`\033[0m] `
#define WARN_COUT `[`<<`\033[33mWarning`<<`\033[0m] `
#define ERROR_COUT `[`<<`\033[31mError`<<`\033[0m] `
#define PURPLE `\033[35m`
#define RED `\033[31m`
#define GREEN `\033[32m`
#define YELLOW `\033[33m`
#define BLUE `\033[34m`
#define COLOR_DEFALUT `\033[0m`
#define MOVEUP(x) printf(`\033[%dA`, (x))
#define CLEAR() printf(`\033[2J`)
#define MOVEUP(x) printf(`\033[%dA`, (x))
#define MOVEDOWN(x) printf(`\033[%dB`, (x))
#define MOVELEFT(y) printf(`\033[%dD`, (y))
#define MOVERIGHT(y) printf(`\033[%dC`,(y))
#define MOVETO(x, y) printf(`\033[%d;%dH`, (x), (y))
#define RESET_CURSOR() printf(`\033[H`)
#define HIDE_CURSOR() printf(`\033[?25l`)
#define SHOW_CURSOR() printf(`\033[?25h`)
#define HIGHT_LIGHT() printf(`\033[7m`)
#define UN_HIGHT_LIGHT() printf(`\033[27m`)
Functions
double * ReadGrd (string filename, GrdHead &grdhead, int extNum)
Read a Surfer Grid data from file.
bool SaveGrd (string filename, GrdHead grdhead, double *data, int extNum, bool savexxyz=false, bool isInfo=true)
Save a Surfer Grid data to file.
void GetKernalMatrix (GrdHead grdhead, double *G, const double rph, int num_thread=4)
Get the Kernal Matrix object.
void GetKernalMatrix_new (GrdHead grdhead, double *G, const double rph, int num_thread=4)
Get the kernel matrix using the new developed formula.
double GetGij (const int i, const int j, double *firstRow, const GrdHead grdhead)
Get the value at i row and the j column of kernel matrix from the first row of the matrix only.
int Getkernel_p2p (GrdHead grdhead, double rph, double **kernel, int num_thread)
Upward continue from plane to plane.
int Getkernel_p2p_new (GrdHead grdhead, double rph, double *kernel_firstRow, int num_thread)
int Getkernel_p2p_new (GrdHead grdhead, double rph, double **kernel, int num_thread)
void UWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
void UWC_p2p_f (string inputfilename, string outputfilename, double height1, double height2, int extNum, string filename_exact)
int UWC_p2p_f (double *inputdata, double *result, GrdHead grdhead, double rph)
int Getkernel_u2p (GrdHead grdhead, double *terrain1, double height2, double **kernel, int num_thread)
int Getkernel_u2p_new (GrdHead grdhead, double *terrain1, double height2, double *nx, double *ny, double *nz, double **kernel, int num_thread)
int Getkernel_p2s_new (GrdHead grdhead, double h1, double *topo2, double **kernel, int num_thread)
void GetPmnij (double *Pmnij, int rows, int cols, double dx, double dy, double rph, double xm, double ym)
void UWC (double *datain, double *dataout, GrdHead grdhead, double **G)
void UWC_Gij (double *b, double *G, double *x, GrdHead grdhead, int num_thread=1)
void UWC_Gji (double *b, double *G, double *x, GrdHead grdhead, int num_thread=1)
void UWC_Gij (double *b, double **G, double *x, int modelnum, int num_thread=1)
void UWC_G_CGLS_Tik (double *b, double **G, double *x, int modelnum, double lambda2, int num_thread=1)
void UWC_Gji (double *b, double **G, double *x, int modelnum, int num_thread=1)
void DWC_u2p (string inputfilename, string outputfilename, double height1, string filename_topo2)
void DWC_p2p_f (string inputfilename, string outputfilename, double height1, double height2, int extNum, double TRP, int num_thread, bool isProgress, bool useOldKernel)
void DWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
void UWC_p2s (string inputfilename, string outputfilename, double height1, string topoFile, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
void DWC_s2p (string inputfilename, string outputfilename, string topo1, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
void DWC_Tikhonov_old (double *G_firstRow, double *dataout, double *indata, double TRP, int kmax, double daierta, GrdHead grdhead, int num_thread)
void DWC_p2p_CGLS (double *G_firstRow, double *x, double *b, GrdHead grdhead, int extNum, double delta, int num_thread)
void DWC_s2p_CGLS (double **G, double *x, double *b, GrdHead grdhead, int extNum, double delta, int num_thread)
void DWC_s2p_Tikhonov (double **G, double *x, double *b, GrdHead grdhead, int extNum, double lambda, int num_thread)
void DWC_s2p_ItegrationIter (double **G, double *x, double *b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double *ExactSolution=NULL)
void DWC_p2p_ItegrationIter (double *G, double *x, double *b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double *ExactSolution=NULL)
void DWC_p2p_LandweberIter (double *G, double *x, double *b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double *ExactSolution=NULL)
void DWC_s2p_LandweberIter (double **G, double *x, double *b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double *ExactSolution=NULL)
double Norm2 (double *x, const int num)
string Path_GetBaseName (string filepath)
string Path_GetExtName (string filepath)
string Path_GetPath (string filepath)
string Path_GetFileName (string filepath)
double Norm2_Gradient (double *result, GrdHead grdhead)
int SaveGrd2VTK (string outputfile, GrdHead grdhead, double *data)
static void StartText ()
static void Text_Axis ()
static void helpINFO ()
static void StartText_artASCII ()
static void OutputErrorinfo (string info)
static void OutputWarninginfo (string info)
Macro Definition Documentation
BLUE
#define BLUE `\033[34m`
Definition at line 35 of file Conti2D.h.
Referenced by ReadGrd().
CLEAR
#define CLEAR() printf(`\033[2J`)
Definition at line 40 of file Conti2D.h.
COLOR_DEFALUT
#define COLOR_DEFALUT `\033[0m`
Definition at line 36 of file Conti2D.h.
Referenced by DWC_p2p(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), helpINFO(), main(), ReadGrd(), SaveGrd(), SaveGrd2VTK(), StartText_artASCII(), MultiProgressBar::Update(), and UWC_p2s().
DWC_CGLS
#define DWC_CGLS 1
Definition at line 23 of file Conti2D.h.
Referenced by DWC_p2p(), DWC_s2p(), and main().
DWC_INTEGRALITERATION
#define DWC_INTEGRALITERATION 3
Definition at line 25 of file Conti2D.h.
Referenced by DWC_p2p(), DWC_s2p(), and main().
DWC_LANDWEBER
#define DWC_LANDWEBER 4
Definition at line 26 of file Conti2D.h.
Referenced by DWC_p2p(), DWC_s2p(), and main().
DWC_TIKHONOV
#define DWC_TIKHONOV 2
Definition at line 24 of file Conti2D.h.
Referenced by DWC_p2p(), DWC_s2p(), and main().
ERROR_COUT [1/2]
#define ERROR_COUT `[`<<`\033[31mError`<<`\033[0m] `
Definition at line 30 of file Conti2D.h.
ERROR_COUT [2/2]
#define ERROR_COUT `[`<<`\033[31mError`<<`\033[0m] `
Definition at line 30 of file Conti2D.h.
GREEN
#define GREEN `\033[32m`
Definition at line 33 of file Conti2D.h.
Referenced by DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), helpINFO(), ReadGrd(), SaveGrd(), and StartText_artASCII().
HIDE_CURSOR
#define HIDE_CURSOR() printf(`\033[?25l`)
Definition at line 54 of file Conti2D.h.
HIGHT_LIGHT
#define HIGHT_LIGHT() printf(`\033[7m`)
Definition at line 57 of file Conti2D.h.
MOVEDOWN
#define MOVEDOWN(x) printf(`\033[%dB`, (x))
Definition at line 44 of file Conti2D.h.
MOVELEFT
#define MOVELEFT(y) printf(`\033[%dD`, (y))
Definition at line 46 of file Conti2D.h.
MOVERIGHT
#define MOVERIGHT(y) printf(`\033[%dC`,(y))
Definition at line 48 of file Conti2D.h.
MOVETO
#define MOVETO(x, y) printf(`\033[%d;%dH`, (x), (y))
Definition at line 50 of file Conti2D.h.
MOVEUP [1/2]
#define MOVEUP(x) printf(`\033[%dA`, (x))
Definition at line 42 of file Conti2D.h.
Referenced by MultiProgressBar::Update().
MOVEUP [2/2]
#define MOVEUP(x) printf(`\033[%dA`, (x))
Definition at line 42 of file Conti2D.h.
PI
#define PI 3.141592653
Definition at line 21 of file Conti2D.h.
Referenced by GetKernalMatrix(), GetKernalMatrix_new(), Getkernel_p2p(), Getkernel_u2p(), Getkernel_u2p_new(), GetPmnij(), and UWC_p2p_f().
PURPLE
#define PURPLE `\033[35m`
Definition at line 31 of file Conti2D.h.
Referenced by helpINFO().
RED
#define RED `\033[31m`
Definition at line 32 of file Conti2D.h.
Referenced by DWC_p2p(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), main(), ReadGrd(), SaveGrd2VTK(), and UWC_p2s().
RESET_CURSOR
#define RESET_CURSOR() printf(`\033[H`)
Definition at line 52 of file Conti2D.h.
SHOW_CURSOR
#define SHOW_CURSOR() printf(`\033[?25h`)
Definition at line 56 of file Conti2D.h.
UN_HIGHT_LIGHT
#define UN_HIGHT_LIGHT() printf(`\033[27m`)
Definition at line 58 of file Conti2D.h.
WARN_COUT
#define WARN_COUT `[`<<`\033[33mWarning`<<`\033[0m] `
Definition at line 29 of file Conti2D.h.
YELLOW
#define YELLOW `\033[33m`
Definition at line 34 of file Conti2D.h.
Function Documentation
DWC_p2p()
void DWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 1669 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, DWC_CGLS, DWC_INTEGRALITERATION, DWC_LANDWEBER, DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_TIKHONOV, Getkernel_p2p_new(), ReadGrd(), RED, GrdHead::rows, and SaveGrd().
Referenced by main().
DWC_p2p_CGLS()
void DWC_p2p_CGLS (double * G_firstRow, double * x, double * b, GrdHead grdhead, int extNum, double delta, int num_thread)
Definition at line 1402 of file Conti2D.cpp.
References GrdHead::cols, Norm2(), GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), UWC_Gij(), and UWC_Gji().
DWC_p2p_f()
void DWC_p2p_f (string inputfilename, string outputfilename, double height1, double height2, int extNum, double TRP, int num_thread, bool isProgress, bool useOldKernel)
Definition at line 976 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, GetKernalMatrix_new(), ReadGrd(), GrdHead::rows, SaveGrd(), and UWC_p2p_f().
Referenced by main().
DWC_p2p_ItegrationIter()
void DWC_p2p_ItegrationIter (double * G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution = NULL)
Definition at line 1768 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), and UWC_Gij().
DWC_p2p_LandweberIter()
void DWC_p2p_LandweberIter (double * G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution = NULL)
Definition at line 1848 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), and UWC_Gij().
DWC_s2p()
void DWC_s2p (string inputfilename, string outputfilename, string topo1, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 1203 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, DWC_CGLS, DWC_INTEGRALITERATION, DWC_LANDWEBER, DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_TIKHONOV, Getkernel_p2s_new(), ReadGrd(), RED, GrdHead::rows, and SaveGrd().
Referenced by main().
DWC_s2p_CGLS()
void DWC_s2p_CGLS (double ** G, double * x, double * b, GrdHead grdhead, int extNum, double delta, int num_thread)
Definition at line 1488 of file Conti2D.cpp.
References GrdHead::cols, Norm2(), GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), UWC_Gij(), and UWC_Gji().
Referenced by DWC_p2p(), and DWC_s2p().
DWC_s2p_ItegrationIter()
void DWC_s2p_ItegrationIter (double ** G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution = NULL)
Definition at line 1317 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), and UWC_Gij().
Referenced by DWC_p2p(), and DWC_s2p().
DWC_s2p_LandweberIter()
void DWC_s2p_LandweberIter (double ** G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution = NULL)
Definition at line 1930 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), and UWC_Gij().
Referenced by DWC_p2p(), and DWC_s2p().
DWC_s2p_Tikhonov()
void DWC_s2p_Tikhonov (double ** G, double * x, double * b, GrdHead grdhead, int extNum, double lambda, int num_thread)
Definition at line 1580 of file Conti2D.cpp.
References GrdHead::cols, Norm2(), GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), UWC_G_CGLS_Tik(), and UWC_Gji().
DWC_Tikhonov_old()
void DWC_Tikhonov_old (double * G_firstRow, double * dataout, double * indata, double TRP, int kmax, double daierta, GrdHead grdhead, int num_thread)
Definition at line 2016 of file Conti2D.cpp.
References GrdHead::cols, GrdHead::rows, and UWC_Gij().
DWC_u2p()
void DWC_u2p (string inputfilename, string outputfilename, double height1, string filename_topo2)
GetGij()
double GetGij (const int i, const int j, double * firstRow, const GrdHead grdhead)
Get the value at i row and the j column of kernel matrix from the first row of the matrix only.
Parameters
i
j
firstRow The first row of the kernel matrix
grdhead
Returns
double
Definition at line 138 of file Conti2D.cpp.
References GrdHead::cols, and GrdHead::rows.
Referenced by UWC_Gij(), and UWC_Gji().
GetKernalMatrix()
void GetKernalMatrix (GrdHead grdhead, double * G, const double rph, int num_thread = 4)
Get the Kernal Matrix object.
Parameters
grdhead
G
rph
num_thread
Definition at line 34 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, and GrdHead::rows.
GetKernalMatrix_new()
void GetKernalMatrix_new (GrdHead grdhead, double * G, const double rph, int num_thread = 4)
Get the kernel matrix using the new developed formula.
Parameters
grdhead
G a 1-d array to store the kernel matrix
rph height of continuation
num_thread
Definition at line 75 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, and GrdHead::rows.
Referenced by DWC_p2p_f().
Getkernel_p2p()
int Getkernel_p2p (GrdHead grdhead, double rph, double ** kernel, int num_thread)
Upward continue from plane to plane.
Parameters
grdhead
rph
kernel
num_thread
Returns
int
Definition at line 197 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, GrdHead::rows, and MultiProgressBar::Update().
Getkernel_p2p_new() [1/2]
int Getkernel_p2p_new (GrdHead grdhead, double rph, double * kernel_firstRow, int num_thread)
Definition at line 305 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, GetPmnij(), and GrdHead::rows.
Getkernel_p2p_new() [2/2]
int Getkernel_p2p_new (GrdHead grdhead, double rph, double ** kernel, int num_thread)
Definition at line 271 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_BAR_BLUE, GrdHead::cols, GetPmnij(), GrdHead::rows, and MultiProgressBar::Update().
Referenced by DWC_p2p(), and UWC_p2p().
Getkernel_p2s_new()
int Getkernel_p2s_new (GrdHead grdhead, double h1, double * topo2, double ** kernel, int num_thread)
Definition at line 237 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_BAR_BLUE, GrdHead::cols, GetPmnij(), GrdHead::rows, and MultiProgressBar::Update().
Referenced by DWC_s2p(), and UWC_p2s().
Getkernel_u2p()
int Getkernel_u2p (GrdHead grdhead, double * terrain1, double height2, double ** kernel, int num_thread)
Definition at line 584 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, and GrdHead::rows.
Getkernel_u2p_new()
int Getkernel_u2p_new (GrdHead grdhead, double * terrain1, double height2, double * nx, double * ny, double * nz, double ** kernel, int num_thread)
Definition at line 626 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, and GrdHead::rows.
GetPmnij()
void GetPmnij (double * Pmnij, int rows, int cols, double dx, double dy, double rph, double xm, double ym)
Definition at line 157 of file Conti2D.cpp.
References PI.
Referenced by Getkernel_p2p_new(), and Getkernel_p2s_new().
helpINFO()
static void helpINFO () [static]
Definition at line 244 of file Conti2D.h.
References COLOR_DEFALUT, GREEN, PURPLE, and Text_Axis().
Referenced by main().
Norm2()
double Norm2 (double * x, const int num)
Definition at line 2167 of file Conti2D.cpp.
Referenced by DWC_p2p_CGLS(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), and DWC_s2p_Tikhonov().
Norm2_Gradient()
double Norm2_Gradient (double * result, GrdHead grdhead)
Definition at line 2176 of file Conti2D.cpp.
References GrdHead::cols, and GrdHead::rows.
Referenced by DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_ItegrationIter(), and DWC_s2p_LandweberIter().
OutputErrorinfo()
static void OutputErrorinfo (string info) [static]
Definition at line 293 of file Conti2D.h.
Referenced by main().
OutputWarninginfo()
static void OutputWarninginfo (string info) [static]
Definition at line 301 of file Conti2D.h.
Referenced by main().
Path_GetBaseName()
string Path_GetBaseName (string filepath)
Definition at line 23 of file Conti2D.cpp.
Path_GetExtName()
string Path_GetExtName (string filepath)
Definition at line 17 of file Conti2D.cpp.
Path_GetFileName()
string Path_GetFileName (string filepath)
Definition at line 5 of file Conti2D.cpp.
Referenced by DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_ItegrationIter(), and DWC_s2p_LandweberIter().
Path_GetPath()
string Path_GetPath (string filepath)
Definition at line 11 of file Conti2D.cpp.
ReadGrd()
double* ReadGrd (string filename, GrdHead & grdhead, int extNum)
Read a Surfer Grid data from file.
Parameters
filename
grdhead
extNum
Returns
double* return data array
Definition at line 721 of file Conti2D.cpp.
References BLUE, GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, GREEN, RED, and GrdHead::rows.
Referenced by DWC_p2p(), DWC_p2p_f(), DWC_s2p(), UWC_p2p(), UWC_p2p_f(), and UWC_p2s().
SaveGrd()
bool SaveGrd (string filename, GrdHead grdhead, double * data, int extNum, bool savexxyz = false, bool isInfo = true)
Save a Surfer Grid data to file.
Parameters
filename
grdhead
data
extNum
savexxyz true: save xyz format simultaneously
isInfo
Returns
true
false
Definition at line 808 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, GREEN, and GrdHead::rows.
Referenced by DWC_p2p(), DWC_p2p_CGLS(), DWC_p2p_f(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p(), DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_s2p_Tikhonov(), UWC_p2p(), UWC_p2p_f(), and UWC_p2s().
SaveGrd2VTK()
int SaveGrd2VTK (string outputfile, GrdHead grdhead, double * data)
Definition at line 2213 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, RED, and GrdHead::rows.
StartText()
static void StartText () [static]
Definition at line 210 of file Conti2D.h.
Referenced by main().
StartText_artASCII()
static void StartText_artASCII () [static]
Definition at line 281 of file Conti2D.h.
References COLOR_DEFALUT, and GREEN.
Referenced by main().
Text_Axis()
static void Text_Axis () [static]
Definition at line 233 of file Conti2D.h.
Referenced by helpINFO().
UWC()
void UWC (double * datain, double * dataout, GrdHead grdhead, double ** G)
Definition at line 954 of file Conti2D.cpp.
References GrdHead::cols, and GrdHead::rows.
UWC_G_CGLS_Tik()
void UWC_G_CGLS_Tik (double * b, double ** G, double * x, int modelnum, double lambda2, int num_thread = 1)
Definition at line 1569 of file Conti2D.cpp.
References UWC_Gij(), and UWC_Gji().
Referenced by DWC_s2p_Tikhonov().
UWC_Gij() [1/2]
void UWC_Gij (double * b, double * G, double * x, GrdHead grdhead, int num_thread = 1)
Definition at line 938 of file Conti2D.cpp.
References GrdHead::cols, GetGij(), and GrdHead::rows.
UWC_Gij() [2/2]
void UWC_Gij (double * b, double ** G, double * x, int modelnum, int num_thread = 1)
Definition at line 900 of file Conti2D.cpp.
Referenced by DWC_p2p_CGLS(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_Tikhonov_old(), UWC_G_CGLS_Tik(), UWC_p2p(), and UWC_p2s().
UWC_Gji() [1/2]
void UWC_Gji (double * b, double * G, double * x, GrdHead grdhead, int num_thread = 1)
Definition at line 921 of file Conti2D.cpp.
References GrdHead::cols, GetGij(), and GrdHead::rows.
UWC_Gji() [2/2]
void UWC_Gji (double * b, double ** G, double * x, int modelnum, int num_thread = 1)
Definition at line 879 of file Conti2D.cpp.
Referenced by DWC_p2p_CGLS(), DWC_s2p_CGLS(), DWC_s2p_Tikhonov(), and UWC_G_CGLS_Tik().
UWC_p2p()
void UWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 400 of file Conti2D.cpp.
References GrdHead::cols, Getkernel_p2p_new(), ReadGrd(), GrdHead::rows, SaveGrd(), and UWC_Gij().
Referenced by main().
UWC_p2p_f() [1/2]
void UWC_p2p_f (string inputfilename, string outputfilename, double height1, double height2, int extNum, string filename_exact)
Definition at line 479 of file Conti2D.cpp.
References GrdHead::cols, ReadGrd(), GrdHead::rows, SaveGrd(), and UWC_p2p_f().
Referenced by DWC_p2p_f(), main(), and UWC_p2p_f().
UWC_p2p_f() [2/2]
int UWC_p2p_f (double * inputdata, double * result, GrdHead grdhead, double rph)
Definition at line 517 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, FFT2d(), IFFT2d(), PI, and GrdHead::rows.
UWC_p2s()
void UWC_p2s (string inputfilename, string outputfilename, double height1, string topoFile, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 320 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, Getkernel_p2s_new(), ReadGrd(), RED, GrdHead::rows, SaveGrd(), and UWC_Gij().
Referenced by main().