Conti2D.cpp File Reference
#include `Conti2D.h`
Functions
string Path_GetFileName (string filepath)
string Path_GetPath (string filepath)
string Path_GetExtName (string filepath)
string Path_GetBaseName (string filepath)
void GetKernalMatrix (GrdHead grdhead, double *G, const double rph, int num_thread)
Get the Kernal Matrix object.
void GetKernalMatrix_new (GrdHead grdhead, double *G, const double rph, int num_thread)
Get the kernel matrix using the new developed formula.
double GetGij (const int i, const int j, double *firstRow, const GrdHead grdhead)
Get the value at i row and the j column of kernel matrix from the first row of the matrix only.
void GetPmnij (double *Pmnij, int rows, int cols, double dx, double dy, double rph, double xm, double ym)
int Getkernel_p2p (GrdHead grdhead, double rph, double **kernel, int num_thread)
Upward continue from plane to plane.
int Getkernel_p2s_new (GrdHead grdhead, double h1, double *topo2, double **kernel, int num_thread)
int Getkernel_p2p_new (GrdHead grdhead, double rph, double **kernel, int num_thread)
int Getkernel_p2p_new (GrdHead grdhead, double rph, double *kernel_firstRow, int num_thread)
void UWC_p2s (string inputfilename, string outputfilename, double height1, string topoFile, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
void UWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
void UWC_p2p_f (string inputfilename, string outputfilename, double height1, double height2, int extNum, string filename_exact)
int UWC_p2p_f (double *inputdata, double *result, GrdHead grdhead, double rph)
int Getkernel_u2p (GrdHead grdhead, double *terrain1, double height2, double **kernel, int num_thread)
int Getkernel_u2p_new (GrdHead grdhead, double *terrain1, double height2, double *nx, double *ny, double *nz, double **kernel, int num_thread)
double * ReadGrd (string filename, GrdHead &grdhead, int extNum)
Read a Surfer Grid data from file.
bool SaveGrd (string filename, GrdHead grdhead, double *data, int extNum, bool savexxyz, bool isInfo)
Save a Surfer Grid data to file.
void UWC_Gji (double *b, double **G, double *x, int modelnum, int num_thread)
void UWC_Gij (double *b, double **G, double *x, int modelnum, int num_thread)
void UWC_Gji (double *b, double *G, double *x, GrdHead grdhead, int num_thread)
void UWC_Gij (double *b, double *G, double *x, GrdHead grdhead, int num_thread)
void UWC (double *datain, double *dataout, GrdHead grdhead, double **G)
void DWC_p2p_f (string inputfilename, string outputfilename, double height1, double height2, int extNum, double TRP, int num_thread, bool isProgress, bool useOldKernel)
void DWC_s2p (string inputfilename, string outputfilename, string topoFile, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
void DWC_s2p_ItegrationIter (double **G, double *x, double *b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double *ExactSolution)
void DWC_p2p_CGLS (double *G_firstRow, double *x, double *b, GrdHead grdhead, int extNum, double delta, int num_thread)
void DWC_s2p_CGLS (double **G, double *x, double *b, GrdHead grdhead, int extNum, double delta, int num_thread)
void UWC_G_CGLS_Tik (double *b, double **G, double *x, int modelnum, double lambda2, int num_thread)
void DWC_s2p_Tikhonov (double **G, double *x, double *b0, GrdHead grdhead, int extNum, double lambda, int num_thread)
void DWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
void DWC_p2p_ItegrationIter (double *G, double *x, double *b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double *ExactSolution)
void DWC_p2p_LandweberIter (double *G, double *x, double *b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double *ExactSolution)
void DWC_s2p_LandweberIter (double **G, double *x, double *b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double *ExactSolution)
void DWC_Tikhonov_old (double *G_firstRow, double *dataout, double *indata, double TRP, int kmax, double daierta, GrdHead grdhead, int num_thread)
double Norm2 (double *x, const int num)
double Norm2_Gradient (double *result, GrdHead grdhead)
int SaveGrd2VTK (string outputfile, GrdHead grdhead, double *data)
Function Documentation
DWC_p2p()
void DWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 1669 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, DWC_CGLS, DWC_INTEGRALITERATION, DWC_LANDWEBER, DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_TIKHONOV, Getkernel_p2p_new(), ReadGrd(), RED, GrdHead::rows, and SaveGrd().
Referenced by main().
DWC_p2p_CGLS()
void DWC_p2p_CGLS (double * G_firstRow, double * x, double * b, GrdHead grdhead, int extNum, double delta, int num_thread)
Definition at line 1402 of file Conti2D.cpp.
References GrdHead::cols, Norm2(), GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), UWC_Gij(), and UWC_Gji().
DWC_p2p_f()
void DWC_p2p_f (string inputfilename, string outputfilename, double height1, double height2, int extNum, double TRP, int num_thread, bool isProgress, bool useOldKernel)
Definition at line 976 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, GetKernalMatrix_new(), ReadGrd(), GrdHead::rows, SaveGrd(), and UWC_p2p_f().
Referenced by main().
DWC_p2p_ItegrationIter()
void DWC_p2p_ItegrationIter (double * G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution)
Definition at line 1768 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), and UWC_Gij().
DWC_p2p_LandweberIter()
void DWC_p2p_LandweberIter (double * G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution)
Definition at line 1848 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), and UWC_Gij().
DWC_s2p()
void DWC_s2p (string inputfilename, string outputfilename, string topoFile, double height2, int extNum, double DWC_parameter, int DWC_method, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 1203 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, DWC_CGLS, DWC_INTEGRALITERATION, DWC_LANDWEBER, DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_TIKHONOV, Getkernel_p2s_new(), ReadGrd(), RED, GrdHead::rows, and SaveGrd().
Referenced by main().
DWC_s2p_CGLS()
void DWC_s2p_CGLS (double ** G, double * x, double * b, GrdHead grdhead, int extNum, double delta, int num_thread)
Definition at line 1488 of file Conti2D.cpp.
References GrdHead::cols, Norm2(), GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), UWC_Gij(), and UWC_Gji().
Referenced by DWC_p2p(), and DWC_s2p().
DWC_s2p_ItegrationIter()
void DWC_s2p_ItegrationIter (double ** G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution)
Definition at line 1317 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), and UWC_Gij().
Referenced by DWC_p2p(), and DWC_s2p().
DWC_s2p_LandweberIter()
void DWC_s2p_LandweberIter (double ** G, double * x, double * b, GrdHead grdhead, int extNum, int num_thread, string outputfile, double iter_number, double * ExactSolution)
Definition at line 1930 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, GREEN, Norm2(), Norm2_Gradient(), Path_GetFileName(), RED, GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), and UWC_Gij().
Referenced by DWC_p2p(), and DWC_s2p().
DWC_s2p_Tikhonov()
void DWC_s2p_Tikhonov (double ** G, double * x, double * b0, GrdHead grdhead, int extNum, double lambda, int num_thread)
Definition at line 1580 of file Conti2D.cpp.
References GrdHead::cols, Norm2(), GrdHead::rows, SaveGrd(), MultiProgressBar::Update(), UWC_G_CGLS_Tik(), and UWC_Gji().
DWC_Tikhonov_old()
void DWC_Tikhonov_old (double * G_firstRow, double * dataout, double * indata, double TRP, int kmax, double daierta, GrdHead grdhead, int num_thread)
Definition at line 2016 of file Conti2D.cpp.
References GrdHead::cols, GrdHead::rows, and UWC_Gij().
GetGij()
double GetGij (const int i, const int j, double * firstRow, const GrdHead grdhead)
Get the value at i row and the j column of kernel matrix from the first row of the matrix only.
Parameters
i
j
firstRow The first row of the kernel matrix
grdhead
Returns
double
Definition at line 138 of file Conti2D.cpp.
References GrdHead::cols, and GrdHead::rows.
Referenced by UWC_Gij(), and UWC_Gji().
GetKernalMatrix()
void GetKernalMatrix (GrdHead grdhead, double * G, const double rph, int num_thread = 4)
Get the Kernal Matrix object.
Parameters
grdhead
G
rph
num_thread
Definition at line 34 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, and GrdHead::rows.
GetKernalMatrix_new()
void GetKernalMatrix_new (GrdHead grdhead, double * G, const double rph, int num_thread = 4)
Get the kernel matrix using the new developed formula.
Parameters
grdhead
G a 1-d array to store the kernel matrix
rph height of continuation
num_thread
Definition at line 75 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, and GrdHead::rows.
Referenced by DWC_p2p_f().
Getkernel_p2p()
int Getkernel_p2p (GrdHead grdhead, double rph, double ** kernel, int num_thread)
Upward continue from plane to plane.
Parameters
grdhead
rph
kernel
num_thread
Returns
int
Definition at line 197 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, GrdHead::rows, and MultiProgressBar::Update().
Getkernel_p2p_new() [1/2]
int Getkernel_p2p_new (GrdHead grdhead, double rph, double ** kernel, int num_thread)
Definition at line 271 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_BAR_BLUE, GrdHead::cols, GetPmnij(), GrdHead::rows, and MultiProgressBar::Update().
Referenced by DWC_p2p(), and UWC_p2p().
Getkernel_p2p_new() [2/2]
int Getkernel_p2p_new (GrdHead grdhead, double rph, double * kernel_firstRow, int num_thread)
Definition at line 305 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, GetPmnij(), and GrdHead::rows.
Getkernel_p2s_new()
int Getkernel_p2s_new (GrdHead grdhead, double h1, double * topo2, double ** kernel, int num_thread)
Definition at line 237 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_BAR_BLUE, GrdHead::cols, GetPmnij(), GrdHead::rows, and MultiProgressBar::Update().
Referenced by DWC_s2p(), and UWC_p2s().
Getkernel_u2p()
int Getkernel_u2p (GrdHead grdhead, double * terrain1, double height2, double ** kernel, int num_thread)
Definition at line 584 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, and GrdHead::rows.
Getkernel_u2p_new()
int Getkernel_u2p_new (GrdHead grdhead, double * terrain1, double height2, double * nx, double * ny, double * nz, double ** kernel, int num_thread)
Definition at line 626 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, PI, and GrdHead::rows.
GetPmnij()
void GetPmnij (double * Pmnij, int rows, int cols, double dx, double dy, double rph, double xm, double ym)
Definition at line 157 of file Conti2D.cpp.
References PI.
Referenced by Getkernel_p2p_new(), and Getkernel_p2s_new().
Norm2()
double Norm2 (double * x, const int num)
Definition at line 2167 of file Conti2D.cpp.
Referenced by DWC_p2p_CGLS(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), and DWC_s2p_Tikhonov().
Norm2_Gradient()
double Norm2_Gradient (double * result, GrdHead grdhead)
Definition at line 2176 of file Conti2D.cpp.
References GrdHead::cols, and GrdHead::rows.
Referenced by DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_ItegrationIter(), and DWC_s2p_LandweberIter().
Path_GetBaseName()
string Path_GetBaseName (string filepath)
Definition at line 23 of file Conti2D.cpp.
Path_GetExtName()
string Path_GetExtName (string filepath)
Definition at line 17 of file Conti2D.cpp.
Path_GetFileName()
string Path_GetFileName (string filepath)
Definition at line 5 of file Conti2D.cpp.
Referenced by DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_ItegrationIter(), and DWC_s2p_LandweberIter().
Path_GetPath()
string Path_GetPath (string filepath)
Definition at line 11 of file Conti2D.cpp.
ReadGrd()
double* ReadGrd (string filename, GrdHead & grdhead, int extNum)
Read a Surfer Grid data from file.
Parameters
filename
grdhead
extNum
Returns
double* return data array
Definition at line 721 of file Conti2D.cpp.
References BLUE, GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, GREEN, RED, and GrdHead::rows.
Referenced by DWC_p2p(), DWC_p2p_f(), DWC_s2p(), UWC_p2p(), UWC_p2p_f(), and UWC_p2s().
SaveGrd()
bool SaveGrd (string filename, GrdHead grdhead, double * data, int extNum, bool savexxyz = false, bool isInfo = true)
Save a Surfer Grid data to file.
Parameters
filename
grdhead
data
extNum
savexxyz true: save xyz format simultaneously
isInfo
Returns
true
false
Definition at line 808 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, GREEN, and GrdHead::rows.
Referenced by DWC_p2p(), DWC_p2p_CGLS(), DWC_p2p_f(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p(), DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_s2p_Tikhonov(), UWC_p2p(), UWC_p2p_f(), and UWC_p2s().
SaveGrd2VTK()
int SaveGrd2VTK (string outputfile, GrdHead grdhead, double * data)
Definition at line 2213 of file Conti2D.cpp.
References GrdHead::bounds, COLOR_DEFALUT, GrdHead::cols, RED, and GrdHead::rows.
UWC()
void UWC (double * datain, double * dataout, GrdHead grdhead, double ** G)
Definition at line 954 of file Conti2D.cpp.
References GrdHead::cols, and GrdHead::rows.
UWC_G_CGLS_Tik()
void UWC_G_CGLS_Tik (double * b, double ** G, double * x, int modelnum, double lambda2, int num_thread)
Definition at line 1569 of file Conti2D.cpp.
References UWC_Gij(), and UWC_Gji().
Referenced by DWC_s2p_Tikhonov().
UWC_Gij() [1/2]
void UWC_Gij (double * b, double ** G, double * x, int modelnum, int num_thread)
Definition at line 900 of file Conti2D.cpp.
Referenced by DWC_p2p_CGLS(), DWC_p2p_ItegrationIter(), DWC_p2p_LandweberIter(), DWC_s2p_CGLS(), DWC_s2p_ItegrationIter(), DWC_s2p_LandweberIter(), DWC_Tikhonov_old(), UWC_G_CGLS_Tik(), UWC_p2p(), and UWC_p2s().
UWC_Gij() [2/2]
void UWC_Gij (double * b, double * G, double * x, GrdHead grdhead, int num_thread)
Definition at line 938 of file Conti2D.cpp.
References GrdHead::cols, GetGij(), and GrdHead::rows.
UWC_Gji() [1/2]
void UWC_Gji (double * b, double ** G, double * x, int modelnum, int num_thread)
Definition at line 879 of file Conti2D.cpp.
Referenced by DWC_p2p_CGLS(), DWC_s2p_CGLS(), DWC_s2p_Tikhonov(), and UWC_G_CGLS_Tik().
UWC_Gji() [2/2]
void UWC_Gji (double * b, double * G, double * x, GrdHead grdhead, int num_thread)
Definition at line 921 of file Conti2D.cpp.
References GrdHead::cols, GetGij(), and GrdHead::rows.
UWC_p2p()
void UWC_p2p (string inputfilename, string outputfilename, double height1, double height2, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 400 of file Conti2D.cpp.
References GrdHead::cols, Getkernel_p2p_new(), ReadGrd(), GrdHead::rows, SaveGrd(), and UWC_Gij().
Referenced by main().
UWC_p2p_f() [1/2]
void UWC_p2p_f (string inputfilename, string outputfilename, double height1, double height2, int extNum, string filename_exact)
Definition at line 479 of file Conti2D.cpp.
References GrdHead::cols, ReadGrd(), GrdHead::rows, SaveGrd(), and UWC_p2p_f().
Referenced by DWC_p2p_f(), main(), and UWC_p2p_f().
UWC_p2p_f() [2/2]
int UWC_p2p_f (double * inputdata, double * result, GrdHead grdhead, double rph)
Definition at line 517 of file Conti2D.cpp.
References GrdHead::bounds, GrdHead::cols, FFT2d(), IFFT2d(), PI, and GrdHead::rows.
UWC_p2s()
void UWC_p2s (string inputfilename, string outputfilename, double height1, string topoFile, int extNum, int num_thread, bool isProgress, bool useOldKernel, string filename_exact)
Definition at line 320 of file Conti2D.cpp.
References COLOR_DEFALUT, GrdHead::cols, Getkernel_p2s_new(), ReadGrd(), RED, GrdHead::rows, SaveGrd(), and UWC_Gij().
Referenced by main().